---
driver:
  name: vagrant
  vagrantfiles:
    - workaround_kitchen_vagrant_bug_181.rb

provisioner:
  name: chef_zero
  encrypted_data_bag_secret_key_path: "enc_data_bag_secret"
  data_bags_path: "data_bags"

platforms:
  #tested on windows
  # - name: centos7
  # desired version; workin with docker
  - name: centos-7.0
    driver:
       network:
          # auto_correct to allow to test both recipes in parallel
          - ["forwarded_port", {guest: 8080, host: 8080, auto_correct: true}]
          - ["private_network", {ip: "122.168.33.9"}]
  # - name: centos7
  #   driver:
  #     box: centos/7
  #     box_check_update: false
  #     ssh:
  #       insert_key: false
  #     network:
  #       # auto_correct to allow to test both recipes in parallel
  #       - ["forwarded_port", {guest: 8080, host: 8080, auto_correct: true}]
  #       - ["private_network", {ip: "122.168.33.9"}]

suites:
  - name: master_basic
    run_list:
      - recipe[ciexjenkins::master]
    attributes: {
      "ciexjenkins": {
        "install_plugins": false,
        "ad": {
          "enabled": true,
          "domain": "projekte.local",
          "server": "projekte-dc1.projekte.local",
          "site": "dc=projekte,dc=local",
          "bindName": "cn=ciex-user01,ou=CI-Extern,dc=projekte,dc=local"
        }
      }
    }
  - name: plugins
    run_list:
      - recipe[ciexjenkins::master]
    attributes: {
      "ciexjenkins": {
        "install_plugins": true
      }
    }
