source 'https://rubygems.org'

gem 'berkshelf'

gem 'test-kitchen'
# gem 'test-kitchen', ">= 1.10.2"
# gem 'test-kitchen', :git => 'https://github.com/tim-pl-m/test-kitchen.git', :ref => '8ec6c7e'
# gem 'test-kitchen', :github => 'tim-pl-m/test-kitchen', :ref => '8ec6c7e'
# gem 'nokogiri', :github => 'tenderlove/nokogiri'

gem 'kitchen-vagrant'
# gem 'chef-sugar'

# gem 'test-kitchen', '~> 1.2'
gem 'kitchen-docker', '~> 2.6.0.rc.0'
# gem 'kitchen-docker'
# gem 'rake'
# gem 'rspec'
gem 'librarian-puppet'

# TODO fix Could not load the 'puppet_apply')
# gem 'kitchen-puppet', ">= 1.42.0"
gem 'kitchen-puppet'
gem 'puppet'
gem 'net-ssh', "~>3.2.0"
# gem 'net-ssh', ">=3.2.0"
# gem 'net-ssh', "~>2.9.2"
# examples for versioning:
# gem "nokogiri", ">= 1.4.2"
# gem "RedCloth", ">= 4.1.0", "< 4.2.0"

gem 'kitchen-vagrant'
#TODO update bundler to coloring in first bundle install?
#gem 'obundler', :git => 'git://github.com/tim-pl-m/bundler.git'