---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:

  # - name: ubuntu
  #   driver:
  #     box: opscode-ubuntu-12.04
  #     box_url: http://files.vagrantup.com/precise32.box

  - name: centos65
    driver:
      box: learningchef/centos65
      box_url: learningchef/centos65
      username: root
      password: root
  #     network:
  #       - ["private_network", {ip: "192.168.33.7"}]


suites:
  - name: default
    run_list:
      - recipe[apache::default]
    attributes:
