rvm:
# - 2.0.0
- 2.1
# - 2.2

sudo: true

# env:
#   matrix:
# # Split up the test-kitchen run to avoid exceeding 50 minutes:
#   - KITCHEN_REGEXP=centos
#   - KITCHEN_REGEXP=debian
#   - KITCHEN_REGEXP=ubuntu

before_script:
- source <(curl -sL https://raw.githubusercontent.com/zuazo/kitchen-in-travis/0.3.0/scripts/start_docker.sh)

script:
- travis_retry bundle exec rake integration:docker
# - travis_retry bundle exec rake integration:docker[$KITCHEN_REGEXP]
