# ---
# driver:
#   name: ec2
#   aws_ssh_key_id: devenv-key
#   security_group_ids: ["sg-835a61ea"]
#   region: eu-central-1
#   # instance_type: t2.medium
#   instance_type: m4.xlarge
#   # instance_type: m4.10xlarge
#   #default
#   # instance_type: t2.micro
#
# transport:
#   ssh_key: ~/.ssh/devenv-key.pem
#
# provisioner:
#   name: chef_zero
#
# platforms:
#   # - name: centos-docker
#   # - name: ubuntu-docker
#   - name: ubuntu-14.04

suites:
  - name: ci-setup
    run_list:
      - recipe[ciexjenkins::master], recipe[ciexdocker::master]
    attributes: {
      "ciexjenkins": {
        "install_plugins": true
      }
    }
