source 'https://supermarket.chef.io'

cookbook "ciexjenkins", github: "tim-pl-m/ProxyCookbook", branch: "ci-role", rel: 'c/cj'
cookbook 'ciexdocker', github: "tim-pl-m/ProxyCookbook", branch: "ci-role", rel: 'c/cd'
# cookbook 'ciexdocker', git: 'https://github.com/tim-pl-m/ProxyCookbook/tree/ci-role', rel: 'c/cd'


# cookbook 'ciexjenkins', git: 'https://ci-cookbooks:'\
# 'qwGTPwE2@scm.adesso.local/scm/git/adesso/CI-Cookbooks', rel: 'ciexjenkins'
# cookbook 'ciexbase', git: 'https://ci-cookbooks:'\
# 'qwGTPwE2@scm.adesso.local/scm/git/adesso/CI-Cookbooks', rel: 'ciexbase'
# cookbook 'git', '= 4.2.2'
# cookbook 'ciexproxy', git: 'https://ci-cookbooks:'\
# 'qwGTPwE2@scm.adesso.local/scm/git/adesso/CI-Cookbooks', rel: 'ciexproxy'
