---
# KITCHEN_LOCAL_YAML=.kitchen.docker.yml kitchen test
driver:
  name: docker

platforms:
  - name: ubuntu-docker
    run_list:
      - recipe[ciexdocker::install]
  # - name: centos
  #   driver_config:
  #     image: centos
  #     platform: rhel
    # run_list:
    # - recipe[yum]
