---
driver:
  name: vagrant
  #TODO check if needed anymore
  #throws error on linux converge
  # vagrantfiles:
  #   - workaround_kitchen_vagrant_bug_181.rb

provisioner:
  name: chef_zero
  # encrypted_data_bag_secret_key_path: "test/fixtures/enc_data_bag_secret"
  # data_bags_path: "test/fixtures/data_bags"

platforms:
  # - name: centos-7.0
  - name: ubuntu-14.04
    # driver:
    #   network:
    #     - ["forwarded_port", {guest: 4243, host: 8084}]
    #     - ["private_network", {ip: "122.168.33.7"}]

suites:
  - name: install
    run_list:
      # - recipe[yum]
      - recipe[ciexdocker::install]
    # attributes: {
    #   "firewall": {
    #     "allow_ssh": true
    #   },
    #   "ciexdocker": {
    #     "allowed_api_client_ip": "10.1.102.121/16"
    #   }
    # }
