---
driver:
  name: ec2
  aws_ssh_key_id: devenv-key
  # aws_ssh_key_id: Tim
  security_group_ids: ["sg-835a61ea"]
  # instance_type: m3.medium
  #default
  # instance_type: t2.micro
  region: eu-central-1
  # iam_profile_name: tim_wieschalla@adesso
  # associate_public_ip: true
  # interface: dns

transport:
 ssh_key: ~/Dropbox/AdessoDropB/zertifikate/aws/devenv-key.pem
 # ssh_key: ~/.ssh/Tim
 # username: ec2-user
 #default?
 # username: ubuntu

#  driver:
#   name: ec2
#   aws_ssh_key_id: id_rsa-aws
#   security_group_ids: ["sg-1a2b3c4d"]
#   region: us-west-2
#   availability_zone: b
#   require_chef_omnibus: true
#   subnet_id: subnet-6e5d4c3b
#   iam_profile_name: chef-client
#   instance_type: m3.medium
#   associate_public_ip: true
#   interface: dns
#
# transport:
#   ssh_key: /path/to/id_rsa-aws
#   connection_timeout: 10
#   connection_retries: 5
#   username: ubuntu


provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  # - name: centos-7

suites:
  - name: default
    run_list:
    attributes:
